<?php
/**
 * Created by PhpStorm.
 * User: weskiller
 * Date: 2018/8/23
 * Time: 14:41
 */

    namespace Weskiller\Stupider\Event\Concrete;

    use Weskiller\Stupider\Event\Abstracts\HttpServerAbstractEventProvider;

    class ServerEventProvider extends HttpServerAbstractEventProvider {

        public function onWorkerStart(\Swoole\Server $server, int $workerId): void {
        }

        public function afterCreateServer(\Weskiller\Stupider\Server\Core $ServerManager): void {
        }

        public function onRequest(\Swoole\Http\Request $req, \Swoole\Http\Response $rep): void {
            parent::onRequest($req, $rep); // TODO: Change the autogenerated stub
        }
    }
